### ISSUE TITLE
iOS Empty WebView

### ISSUE THREAD

**Issue by MarcinWad** [przelewy24/p24-mobile-lib-flutter#15]
Hello,
I try to implement flutter mobile Payment in my app.

Everything works on Android well. After running it in Xcode and compiling after i try to open new Transaction which is involved with

` TrnDirectParams params = TrnDirectParams(transactionParams: tr, isSandbox: false);`

`P24SDK.trnDirect(params).then((response) async {  some code} `

I get a simple white screen with Title Przelewy24 and nothing more. Any clues?

**Comment by MarcinWad** [comment]
To future readers, it will not work in Testing (Debug) mode even when "Debug Executable" is unchecked.

**Comment by mareklat** [comment]
Does the problem occur in the sample project?

**Comment by MarcinWad** [comment]
Yes.
Second problem is that implementing this lib in application will not pass Apple Review and App will be rejected because it is not In-App Payment.

**Comment by mareklat** [comment]
Could you please show me an example implementation that causes the above mentioned error?

About second issue, please refer to this document: https://developer.apple.com/design/human-interface-guidelines/in-app-purchase

Please pay special attention to the terms Consumable and Nonconsumable. Make sure your application meets the relevant guidelines.

**Comment by mareklat** [comment]
Closed due to no response
