### ISSUE TITLE
Flutter Lib imports outdated GMS services which prevents app from update in Play Store

### ISSUE THREAD

**Issue by MarcinWad** [przelewy24/p24-mobile-lib-flutter#16]
Adding p24_sdk adds following dependencies:

```
+--- project :p24_sdk
|    +--- io.flutter:flutter_embedding_debug:1.0.0-b84ad1ad30cca8d303b4bcb2bbd77573e4d66122 (*)
|    +--- pl.przelewy24:p24lib:+ -> 3.5.56
|    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21 -> 1.8.22 (*)
|    +--- androidx.appcompat:appcompat:1.3.1 (*)
|    \--- com.google.android.gms:play-services-wallet:16.+ -> 16.0.1
|         +--- com.google.android.gms:play-services-base:16.0.1 -> 18.0.0 (*)
|         +--- com.google.android.gms:play-services-basement:16.0.1 -> 18.0.0 (*)
|         +--- com.google.android.gms:play-services-identity:16.0.0
|         |    +--- com.google.android.gms:play-services-base:16.0.1 -> 18.0.0 (*)
|         |    \--- com.google.android.gms:play-services-basement:16.0.1 -> 18.0.0 (*)
|         +--- com.google.android.gms:play-services-maps:16.0.0
|         |    +--- com.google.android.gms:play-services-base:16.0.1 -> 18.0.0 (*)
|         |    \--- com.google.android.gms:play-services-basement:16.0.1 -> 18.0.0 (*)
|         \--- com.google.android.gms:play-services-tasks:16.0.1 -> 18.0.1 (*)
```

This adds play-services-maps to final application which prevents it's update in Google Play Console because of outdated and unmaintained version. Play console reports:

`The developer of Maps SDK for Android (com.google.android.gms:play-services-maps) has reported version 16.0.0 as outdated. After 90 days from releasing this version of your app, you won't be able to release new versions which contain this SDK until you upgrade to a newer version (17.0.0+).`

Manually fixing dependecny in p24_sdk fixes problem:
`implementation 'com.google.android.gms:play-services-wallet:17.+'`

**Comment by mareklat** [comment]
The "pl.przelewy24:p24lib" library has just received an update that solves this problem. Please update project to check effect.

**Comment by badvans** [comment]
+1, this issue will block any app deployment to Google Play Store when January ends

**Comment by mareklat** [comment]
The library received an update with a bumped version of google play services
