### ISSUE TITLE
Issue when select pay with PeoPay Application

### ISSUE THREAD

**Issue by pskital** [przelewy24/p24-mobile-lib-flutter#18]
[
![IMG_1484](https://github.com/przelewy24/p24-mobile-lib-flutter/assets/6280766/0dc787dd-2be5-4473-98b9-3a2d10724e6b)
]

**Comment by mareklat** [comment]
@pskital This issue is related to bank page. This issue has been reported and we are waiting for fix.

**Comment by przelewy24mobile** [comment]
Close due to no response
