### ISSUE TITLE
Invalid Executable. The executable 'Runner.app/Frameworks/P24.framework/P24' contains bitcode.

### ISSUE THREAD

**Issue by bykup** [przelewy24/p24-mobile-lib-flutter#20]
After updating to XCode to version 16, I'm unable to upload my app to app store.

I'm receiving an error that the framework contains bitcode.

**Comment by maciogg** [comment]
Same issue. Any solution?

**Comment by przelewy24mobile** [comment]
Please check version 1.0.59, this should solve problem

**Comment by przelewy24mobile** [comment]
Closed due to no response
