### ISSUE TITLE
Missing P24Merchant

### ISSUE THREAD

**Issue by JJMPdsk** [przelewy24/p24-mobile-lib-flutter#3]
Hi,

I'm currently working on a project requiring P24 support. I've been following readme, but from nowhere at any point I can import interface P24Merchant, so I'm kinda stuck with that.

I saw the dates on new releases and last change of readme - is it up-to-date? 
I also downloaded whole repo and searched for P24Merchant, so i could continue with your instructions, however nothing besides readme found. Any ideas, tips?

Thank you.

**Comment by mareklat** [comment]
@JJMPdsk Thank you for reporting. By mistake, this part of the documentation appeared in the repository. The fixes are now on github, coming soon on pub.dev.
