### ISSUE TITLE
P24 webview crashes on trying to add a card

### ISSUE THREAD

**Issue by kurmasan** [przelewy24/p24-mobile-lib-flutter#4]
Hi,
We are using flutter native library p24_sdk. We have sandbox environment set up, where we use:
- redirection to credit card payment in p24 webview with or without saving credit card data,
- saving credit card data,
- paying with already saved credit card.
With sandbox enabled everything works fine.

Problems occur, when we turn the sandbox off. So far operations, that do not involve saving card seem to work properly. Issue is with tries to save card data either while paying with a card or just saving credit card reference.
The web view stops at "awaiting confirmation from bank" and does not close itself. On our side backend recieves information, saves the card data and sends notification. If we close the webview window card is added.

It occurs almost always on phones with android and almost never, but sometimes does too on iphones.
If we enter invalid credit card data e.g. cvc webview is closed normally.

At the beginning we were using version 1.0.20, when the problem occured, we upgraded to 1.0.29 and it didn't help. 
Any tips or ideas?

Thanks in advance :)

**Comment by mareklat** [comment]
@kurmasan Hi, could you provide us more info about how you register transaction? What library methods do you use?

**Comment by kurmasan** [comment]
Hi,
of course. When trying to add a card or when we try to save card during direct credit card payment (skipping the web view choosing of payment method) we use:
P24SDK.trnRequest(
      TrnRequestParams(
        token: token,
        isSandbox: isSandbox));
Where token we recieve from backend and isSandbox is of course false in this case.

Process of registration and verification transactions is handled by our backend via REST API.
To register transaction we are using register endpoint with parameter “method” set as 218 to redirect straight to card payment method -  /api/v1/transaction/register 
Received token is used by our application along with the p24 flutter lib library. After successful payment and verification 3ds,  we are getting confirmation to established endpoints urlStatus and additionalCardNotification. So payment is confirmed, and authorized but application stuck after 3ds authorization on screen “waiting for confirmation from you bank”

On June 16 between 13:36 and 13:40 GTM+2 I've adding a card 3 times. In one of them I purposefully entered wrong card info and web view closed, on two others I've entered correct data and web view was stuck.
Thanks for quick response :)

**Comment by mareklat** [comment]
This looks like a problem on our backend side, not directly in the library. Probably the waiting page does not send a notification to the library. I would like to ask you to send your bug report at https://www.przelewy24.pl/pomoc/formularz-kontaktowy. Please indicate this issue so that technical support knows the context.
