### ISSUE TITLE
Problem with Android dependencies.

### ISSUE THREAD

**Issue by LukaszKoszentka** [przelewy24/p24-mobile-lib-flutter#6]
Hi, I have a problem with it building flutter on Android .

Can you help me? 

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve pl.przelewy24:p24lib:+.
     Required by:
         project :app > project :p24_sdk
      > Failed to list versions for pl.przelewy24:p24lib.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/pl/przelewy24/p24lib/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/pl/przelewy24/p24lib/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/pl/przelewy24/p24lib/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by mareklat** [comment]
Hi, this address: https://mobile.przelewy24.pl/p24lib.gradle is accessible from machine where you try to build project?

**Comment by LukaszKoszentka** [comment]
Yes, I can reach this file.

**Comment by mareklat** [comment]
@LukaszKoszentka Try rebuild again. There was probably a temporary connection problem

**Comment by Dizziest** [comment]
I've got the same problem since yesterday. Looks like a bintray is down. Can we do anything about this?

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve pl.przelewy24:p24lib:+.
     Required by:
         project :app > project :flutter > project :p24_sdk
      > Failed to list versions for pl.przelewy24:p24lib.
         > Unable to load Maven meta-data from https://dl.bintray.com/microsoftazuremobile/SDK/pl/przelewy24/p24lib/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/microsoftazuremobile/SDK/pl/przelewy24/p24lib/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/microsoftazuremobile/SDK/pl/przelewy24/p24lib/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by mareklat** [comment]
@Dizziest p24_sdk is not hosted on bintray but on github packages. It is very likely that the build process still crashes when trying to connect to the bintray server. Is this problem still occurring?

**Comment by Dizziest** [comment]
Yup, it is still occuring. Currently overpassed the problem by putting gradle in offline mode.

**Comment by LukaszKoszentka** [comment]
Hi, this is still occurring for me also.

**Comment by mareklat** [comment]
@LukaszKoszentka @Dizziest Does problem also occur in the example project?

**Comment by mareklat** [comment]
Closed due to no response
