### ISSUE TITLE
Split payment availibility

### ISSUE THREAD

**Issue by Ludwiczek2507** [przelewy24/p24-mobile-lib-flutter#8]
Hi, 

Is it possible to add SdkConfig.splitPaymentEnabled flag ?

Thanks

**Comment by mareklat** [comment]
Hi,

Yes, it is possible. I added this to our backlog. Changes should appear in the first half of May.

**Comment by mareklat** [comment]
Hi, split payment function added. To activate it, change the appropriate flag in P24SdkConfig.
